default:
  helmet_data: "C:/../helmet-results"
  forecast_zonedata_path: "C:/.../Syottodata"
  housing_cost: "AsKustannukset_01062021.xlsx"
  income_data: "tulotiedot_2016_korjattu.xlsx"
  present_scenario: "2018_agentti"
  present_name: "2018 Nykytila"

2040_ve0-2040_ve1:
  projected_scenario: "2040_ve1_agentti"
  baseline_scenario: "2040_ve0_agentti"
  projected_name: "2040 1. luonnos"
  baseline_name: "2040 Vertailupohja"
